version: '3'
services:
    nginx:
        container_name: delocatarios-nginx
        image: delocatarios-nginx:v1
        restart: always
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        environment:
            - VIRTUAL_HOST=delocatarios.com
            - LETSENCRYPT_HOST=delocatarios.com
            - LETSENCRYPT_EMAIL=victorlt.xd3@gmail.com
        expose:
            - "80"
            - "443"
        networks:
            - nginx-proxy
            - net-front-delocatarios
    delocatarios:
        build: app/.
        container_name: delocatarios
        restart: always
        command:
            "npm run start"
        networks:
            - net-front-delocatarios

networks:
     net-front-delocatarios:
     nginx-proxy:
        external:
            name: ubuntu_nginx-proxy
