language: node_js
node_js:
  - "v14.13.0"
cache:
  directories:
    - "node_modules"
script:
  - echo "Deploy don pale project"
env:
  global:
    - URL_BACKEND=http://delocatarios.com:1337
install:
  - npm install
  - npm i -g firebase-tools
  - npm run generate
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
